# Generated by Django 5.2.9 on 2025-12-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicallead',
            name='last_contact',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='next_action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='next_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contact',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='lead_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.leadtype'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadtype'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='leads.tag'),
        ),
    ]
