# Generated by Django 5.2.9 on 2025-12-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_load_initial_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='leads_city_name'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country'], name='leads_city_country'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['temperature'], name='leads_lead_temperature'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_action_date'], name='leads_lead_next_action_date'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_at'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['city'], name='leads_lead_city'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type'], name='leads_lead_type'),
        ),
    ]
