# Generated by Django 5.2.9 on 2025-12-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_city_leads_city_name_city_leads_city_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_template', models.TextField(default='Research leads in {city} for event promotion.', help_text='Use {city} and {lead_types} as placeholders.')),
            ],
            options={
                'verbose_name': 'Research Prompt Config',
            },
        ),
        migrations.CreateModel(
            name='ResearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gemini_interaction_id', models.CharField(blank=True, max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('leads_created', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_jobs', to='leads.city')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('city',), name='unique_active_research_per_city')],
            },
        ),
    ]
