# Generated by Django 5.2.9 on 2025-12-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_add_poll_research_periodic_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpromptconfig',
            name='prompt_template',
            field=models.TextField(default='Research leads in {city} for event promotion.\n\nLead types: {lead_types}\n\nOutput schema: {schema}', help_text='Use {city}, {lead_types}, and {schema} as placeholders.'),
        ),
    ]
