# Generated by Django 5.2.9 on 2025-12-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_researchjob_raw_result_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leads_lead_email'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='leads_lead_phone'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['instagram'], name='leads_lead_instagram'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['telegram'], name='leads_lead_telegram'),
        ),
    ]
