# Generated by Django 5.2.9 on 2025-12-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_leads_lead_email_lead_leads_lead_phone_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_city',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_type',
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['website'], name='leads_lead_website'),
        ),
    ]
