# Generated by Django 5.2.9 on 2025-12-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_historicalaction_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': [models.OrderBy(models.F('due_date'), nulls_last=True), 'created_at']},
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['created_at'], name='leads_action_created_at'),
        ),
    ]
