# Generated by Django 5.2.9 on 2025-12-19 08:57

from django.db import migrations
from django.db.models import Q


def migrate_lead_actions_to_action_model(apps, schema_editor):
    """Migrate next_action and next_action_date from Lead to Action model."""
    Lead = apps.get_model("leads", "Lead")
    Action = apps.get_model("leads", "Action")

    actions_to_create = []
    for lead in Lead.objects.filter(
        (Q(next_action__isnull=False) & ~Q(next_action="")) | Q(next_action_date__isnull=False)
    ):
        description = lead.next_action if lead.next_action else "Follow up"
        actions_to_create.append(
            Action(
                lead=lead,
                description=description,
                due_date=lead.next_action_date,
                status="pending",
            )
        )

    if actions_to_create:
        Action.objects.bulk_create(actions_to_create)


def reverse_migration(apps, schema_editor):
    """Reverse migration - copy Action data back to Lead fields."""
    Lead = apps.get_model("leads", "Lead")
    Action = apps.get_model("leads", "Action")

    # For each lead, get the first pending action and copy it back
    for action in Action.objects.filter(status="pending").select_related("lead"):
        lead = action.lead
        # Only update if Lead fields are empty (don't overwrite)
        if not lead.next_action and not lead.next_action_date:
            lead.next_action = action.description
            lead.next_action_date = action.due_date
            lead.save(update_fields=["next_action", "next_action_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0013_alter_action_options_action_leads_action_created_at"),
    ]

    operations = [
        migrations.RunPython(migrate_lead_actions_to_action_model, reverse_migration),
    ]
