# Generated by Django 5.2.9 on 2025-12-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0014_migrate_lead_actions_to_action_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="description",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="historicalaction",
            old_name="description",
            new_name="name",
        ),
        migrations.AddField(
            model_name="action",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalaction",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
