# Generated by Django 5.2.9 on 2025-12-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_rename_action_description_to_name_add_notes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_next_action_date',
        ),
        migrations.RemoveField(
            model_name='historicallead',
            name='next_action',
        ),
        migrations.RemoveField(
            model_name='historicallead',
            name='next_action_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_action',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_action_date',
        ),
    ]
