# Generated by Django 5.2.9 on 2025-12-25 19:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_remove_next_action_fields_from_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template identifier (e.g., 'Initial Outreach')", max_length=255, unique=True)),
                ('subject', models.CharField(help_text='Subject line. Use {lead.name}, {lead.city}, etc.', max_length=255)),
                ('body', models.TextField(help_text='Email body. Use {lead.name}, {lead.city}, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmailTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Template identifier (e.g., 'Initial Outreach')", max_length=255)),
                ('subject', models.CharField(help_text='Subject line. Use {lead.name}, {lead.city}, etc.', max_length=255)),
                ('body', models.TextField(help_text='Email body. Use {lead.name}, {lead.city}, etc.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical email template',
                'verbose_name_plural': 'historical email templates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(help_text='Sender email address', max_length=254)),
                ('to', models.JSONField(help_text='List of recipient email addresses')),
                ('bcc', models.JSONField(blank=True, default=list, help_text='List of BCC email addresses')),
                ('subject', models.CharField(help_text='Rendered subject at send time', max_length=255)),
                ('body', models.TextField(help_text='Rendered body at send time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if sending failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_sent', to='leads.lead')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to='leads.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Sent',
                'verbose_name_plural': 'Emails Sent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='leads_emailsent_status'), models.Index(fields=['sent_at'], name='leads_emailsent_sent_at'), models.Index(fields=['created_at'], name='leads_emailsent_created_at')],
            },
        ),
    ]
