# Generated by Django 5.2.9 on 2025-12-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_add_email_template_and_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian'), ('es', 'Spanish'), ('de', 'German'), ('fr', 'French')], default='en', help_text='Language of the template', max_length=5),
        ),
        migrations.AddField(
            model_name='historicalemailtemplate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian'), ('es', 'Spanish'), ('de', 'German'), ('fr', 'French')], default='en', help_text='Language of the template', max_length=5),
        ),
    ]
