# Generated by Django 5.2.9 on 2025-12-29 13:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_emailtemplate_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmailDraft',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('from_email', models.EmailField(blank=True, help_text='Sender email address (defaults to DEFAULT_FROM_EMAIL)', max_length=254)),
                ('to', models.JSONField(default=list, help_text='List of recipient email addresses')),
                ('bcc', models.JSONField(blank=True, default=list, help_text='List of BCC email addresses')),
                ('subject', models.CharField(help_text='Email subject', max_length=255)),
                ('body', models.TextField(help_text='Email body')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.lead')),
                ('template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.emailtemplate')),
            ],
            options={
                'verbose_name': 'historical Email Draft',
                'verbose_name_plural': 'historical Email Drafts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(blank=True, help_text='Sender email address (defaults to DEFAULT_FROM_EMAIL)', max_length=254)),
                ('to', models.JSONField(default=list, help_text='List of recipient email addresses')),
                ('bcc', models.JSONField(blank=True, default=list, help_text='List of BCC email addresses')),
                ('subject', models.CharField(help_text='Email subject', max_length=255)),
                ('body', models.TextField(help_text='Email body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_drafts', to='leads.lead')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_drafts', to='leads.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Draft',
                'verbose_name_plural': 'Email Drafts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['created_at'], name='leads_emaildraft_created'), models.Index(fields=['updated_at'], name='leads_emaildraft_updated')],
            },
        ),
    ]
