# Generated by Django 5.2.9 on 2025-12-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_historicalemaildraft_emaildraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildraft',
            name='from_email',
            field=models.CharField(blank=True, help_text='Sender email address (defaults to DEFAULT_FROM_EMAIL)', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalemaildraft',
            name='from_email',
            field=models.CharField(blank=True, help_text='Sender email address (defaults to DEFAULT_FROM_EMAIL)', max_length=255),
        ),
    ]
