# Generated by Django 5.2.9 on 2026-04-03 10:06

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_alter_emaildraft_from_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsent',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the send', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GmailConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The Gmail address connected', max_length=254)),
                ('refresh_token', encrypted_fields.fields.EncryptedTextField(help_text='OAuth2 refresh token (encrypted at rest)')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False on auth errors')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gmail Connection',
                'verbose_name_plural': 'Gmail Connections',
            },
        ),
    ]
