# Generated by Django 5.2.9 on 2026-04-04 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_emailsent_sent_by_gmailconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='', help_text='HTML signature content. Appended to all outgoing emails.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_signature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Signature',
                'verbose_name_plural': 'Email Signatures',
            },
        ),
    ]
