# Generated by Django 5.2.9 on 2026-04-15 09:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_emailsignature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="Person name or label (e.g., 'Primary', 'Booker')", max_length=255)),
                ('role', models.CharField(blank=True, help_text="Role at the organization (e.g., 'booker')", max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('telegram', models.CharField(blank=True, help_text='Telegram username or link', max_length=255)),
                ('instagram', models.CharField(blank=True, help_text='Instagram handle', max_length=255)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.lead')),
            ],
            options={
                'verbose_name': 'historical contact',
                'verbose_name_plural': 'historical contacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Person name or label (e.g., 'Primary', 'Booker')", max_length=255)),
                ('role', models.CharField(blank=True, help_text="Role at the organization (e.g., 'booker')", max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('telegram', models.CharField(blank=True, help_text='Telegram username or link', max_length=255)),
                ('instagram', models.CharField(blank=True, help_text='Instagram handle', max_length=255)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='leads.lead')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
                'indexes': [models.Index(fields=['email'], name='leads_contact_email'), models.Index(fields=['phone'], name='leads_contact_phone'), models.Index(fields=['instagram'], name='leads_contact_instagram'), models.Index(fields=['telegram'], name='leads_contact_telegram'), models.Index(fields=['website'], name='leads_contact_website')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('lead',), name='leads_contact_unique_primary_per_lead')],
            },
        ),
    ]
