# Generated by Django 5.2.9 on 2026-04-15 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_backfill_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact this draft is addressed to (if known)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_drafts', to='leads.contact'),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact this email was addressed to (if known)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to='leads.contact'),
        ),
        migrations.AddField(
            model_name='historicalemaildraft',
            name='contact',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Contact this draft is addressed to (if known)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.contact'),
        ),
    ]
