# Local Docker Compose configuration for end-users
# Usage: ./local_wizard.sh

services:
  redis:
    image: redis:7-alpine
    container_name: microcrm_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data

  web:
    build: .
    container_name: microcrm_web
    command:
      - sh
      - -c
      - |
        python manage.py migrate --noinput &&
        python manage.py bootstrap &&
        python manage.py seed &&
        gunicorn crm.wsgi:application --bind 0.0.0.0:8000 --workers 2 --access-logfile -
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - REDIS_HOST=redis
      - CELERY_TASK_ALWAYS_EAGER=False
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery:
    build: .
    container_name: microcrm_celery
    command: celery -A crm worker -l INFO
    env_file:
      - .env
    environment:
      - DEBUG=True
      - REDIS_HOST=redis
      - CELERY_TASK_ALWAYS_EAGER=False
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started
    restart: unless-stopped

  beat:
    build: .
    container_name: microcrm_beat
    command: celery -A crm beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    environment:
      - DEBUG=True
      - REDIS_HOST=redis
      - CELERY_TASK_ALWAYS_EAGER=False
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started
    restart: unless-stopped

volumes:
  redis_data:
