#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Banner
echo -e "${CYAN}"
echo "  __  __ _                  ____ ____  __  __ "
echo " |  \/  (_) ___ _ __ ___   / ___|  _ \|  \/  |"
echo " | |\/| | |/ __| '__/ _ \ | |   | |_) | |\/| |"
echo " | |  | | | (__| | | (_) || |___|  _ <| |  | |"
echo " |_|  |_|_|\___|_|  \___/  \____|_| \_\_|  |_|"
echo -e "${NC}"
echo -e "${BOLD}Production Setup Wizard${NC}"
echo ""

ENV_FILE=".env.prod"
COMPOSE_FILE="compose.prod.yaml"

# Check for Docker
check_docker() {
    echo -e "${BLUE}Checking for Docker...${NC}"
    if ! command -v docker &> /dev/null; then
        echo -e "${RED}Docker is not installed.${NC}"
        echo "Install Docker: https://docs.docker.com/engine/install/"
        exit 1
    fi

    if ! docker info &> /dev/null; then
        echo -e "${RED}Docker daemon is not running.${NC}"
        exit 1
    fi

    if docker compose version &> /dev/null; then
        COMPOSE_CMD="docker compose"
    elif command -v docker-compose &> /dev/null; then
        COMPOSE_CMD="docker-compose"
    else
        echo -e "${RED}Docker Compose is not available.${NC}"
        exit 1
    fi

    echo -e "${GREEN}Docker is ready.${NC}"
}

# Generate random password
generate_password() {
    openssl rand -base64 24 2>/dev/null | tr -d '/+=' | head -c 32
}

# Generate .env.prod file
generate_env() {
    echo ""
    echo -e "${BLUE}Configuring production environment...${NC}"

    # Check if .env.prod already exists
    if [ -f "$ENV_FILE" ]; then
        echo -e "${YELLOW}An existing $ENV_FILE file was found.${NC}"
        read -p "Do you want to overwrite it? (y/N): " overwrite
        if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
            echo -e "${GREEN}Keeping existing configuration.${NC}"
            return
        fi
    fi

    # === REQUIRED CONFIGURATION ===
    echo ""
    echo -e "${BOLD}=== Required Configuration ===${NC}"

    # Domain
    echo ""
    echo -e "${CYAN}Enter your domain (e.g., crm.example.com):${NC}"
    echo -e "This will be used for HTTPS certificates and Django settings."
    read -p "Domain: " domain
    if [ -z "$domain" ]; then
        echo -e "${RED}Domain is required.${NC}"
        exit 1
    fi

    # Superuser
    echo ""
    echo -e "${CYAN}Configure admin account:${NC}"
    read -p "Admin username [admin]: " admin_user
    admin_user=${admin_user:-admin}
    read -p "Admin email [admin@${domain}]: " admin_email
    admin_email=${admin_email:-admin@${domain}}
    read -s -p "Admin password [auto-generate]: " admin_pass
    echo ""
    if [ -z "$admin_pass" ]; then
        admin_pass=$(generate_password)
        echo -e "${YELLOW}Generated admin password: ${admin_pass}${NC}"
        echo -e "${YELLOW}Save this password securely!${NC}"
    fi

    # Database password
    echo ""
    echo -e "${CYAN}Database configuration:${NC}"
    read -s -p "PostgreSQL password [auto-generate]: " db_pass
    echo ""
    if [ -z "$db_pass" ]; then
        db_pass=$(generate_password)
        echo -e "${YELLOW}Generated database password (stored in $ENV_FILE)${NC}"
    fi

    # Gemini API Key
    echo ""
    echo -e "${CYAN}AI Research (Gemini API):${NC}"
    echo -e "Get your API key from: ${BOLD}https://aistudio.google.com/app/apikey${NC}"
    read -p "GEMINI_API_KEY (or press Enter to skip): " gemini_key

    # === OPTIONAL CONFIGURATION ===
    echo ""
    echo -e "${BOLD}=== Optional Configuration ===${NC}"

    # Google SSO
    echo ""
    echo -e "${CYAN}Google SSO (optional):${NC}"
    read -p "Enable Google SSO? (y/N): " enable_sso
    if [[ "$enable_sso" =~ ^[Yy]$ ]]; then
        echo -e "Get credentials from: ${BOLD}https://console.cloud.google.com/apis/credentials${NC}"
        read -p "Google Client ID: " google_client_id
        read -p "Google Client Secret: " google_client_secret
        read -p "Google Project ID: " google_project_id
        read -p "Superuser email list (comma-separated): " google_superuser_list
    fi

    # Generate secret key
    secret_key=$(generate_password)$(generate_password)

    # Write .env.prod file
    cat > "$ENV_FILE" << EOF
# ===========================================
# MicroCRM Production Configuration
# Generated by prod_wizard.sh
# ===========================================

# Domain - single source of truth
# ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS are derived from this in settings.py
DOMAIN=${domain}

# Superuser
SUPERUSER_USERNAME=${admin_user}
SUPERUSER_EMAIL=${admin_email}
SUPERUSER_PASSWORD=${admin_pass}

# Django
SECRET_KEY=${secret_key}
DEBUG=False
SITE_NAME=MicroCRM

# Database (PostgreSQL)
DB_NAME=microcrm
DB_USER=microcrm
DB_PASSWORD=${db_pass}
DB_HOST=postgres
DB_PORT=5432

# Redis & Celery
REDIS_HOST=redis
REDIS_PORT=6379
CELERY_TASK_ALWAYS_EAGER=False

# API
API_KEY=$(generate_password)

# Gemini AI
GEMINI_API_KEY=${gemini_key}

# Google SSO (optional)
GOOGLE_SSO_CLIENT_ID=${google_client_id:-}
GOOGLE_SSO_CLIENT_SECRET=${google_client_secret:-}
GOOGLE_SSO_PROJECT_ID=${google_project_id:-}
GOOGLE_SSO_SUPERUSER_LIST=${google_superuser_list:-}
EOF

    echo -e "${GREEN}Configuration saved to $ENV_FILE${NC}"
}

# Start services
start_services() {
    echo ""
    echo -e "${BLUE}Building and starting production services...${NC}"
    echo ""
    echo -e "This will start:"
    echo -e "  ${CYAN}- Caddy${NC}    (reverse proxy + HTTPS)"
    echo -e "  ${CYAN}- PostgreSQL${NC} (database)"
    echo -e "  ${CYAN}- Redis${NC}   (message broker)"
    echo -e "  ${CYAN}- Web${NC}     (Django/Gunicorn)"
    echo -e "  ${CYAN}- Celery${NC}  (background worker)"
    echo -e "  ${CYAN}- Beat${NC}    (task scheduler)"
    echo ""
    echo -e "${YELLOW}First run may take several minutes to build...${NC}"
    echo ""

    # Load DOMAIN from .env.prod for display
    source "$ENV_FILE"

    $COMPOSE_CMD -f "$COMPOSE_FILE" up --build -d

    echo ""
    echo -e "${GREEN}Production deployment complete!${NC}"
    echo ""
    echo -e "${BOLD}Your application is now available at:${NC}"
    echo -e "  ${CYAN}https://${DOMAIN}${NC}"
    echo ""
    echo -e "${BOLD}Admin panel:${NC}"
    echo -e "  ${CYAN}https://${DOMAIN}/admin/${NC}"
    echo ""
    echo -e "${BOLD}API documentation:${NC}"
    echo -e "  ${CYAN}https://${DOMAIN}/api/docs${NC}"
    echo ""
    echo -e "${YELLOW}Note: HTTPS certificates may take a minute to provision.${NC}"
    echo ""
    echo -e "${BOLD}Useful commands:${NC}"
    echo -e "  View logs:     ${CYAN}./prod_wizard.sh logs${NC}"
    echo -e "  Stop:          ${CYAN}./prod_wizard.sh stop${NC}"
    echo -e "  Restart:       ${CYAN}./prod_wizard.sh restart${NC}"
    echo ""

    # Show container status
    echo -e "${BOLD}Container status:${NC}"
    $COMPOSE_CMD -f "$COMPOSE_FILE" ps
}

# Stop services
stop_services() {
    echo -e "${BLUE}Stopping production services...${NC}"
    $COMPOSE_CMD -f "$COMPOSE_FILE" down
    echo -e "${GREEN}All services stopped.${NC}"
}

# Show logs
show_logs() {
    $COMPOSE_CMD -f "$COMPOSE_FILE" logs -f
}

# Show status
show_status() {
    $COMPOSE_CMD -f "$COMPOSE_FILE" ps
}

# Update (pull latest and restart)
update_services() {
    echo -e "${BLUE}Updating MicroCRM...${NC}"
    git pull
    $COMPOSE_CMD -f "$COMPOSE_FILE" up --build -d
    echo -e "${GREEN}Update complete!${NC}"
}

# Backup database
backup_db() {
    timestamp=$(date +%Y%m%d_%H%M%S)
    backup_file="backup_${timestamp}.sql"
    echo -e "${BLUE}Creating database backup...${NC}"
    $COMPOSE_CMD -f "$COMPOSE_FILE" exec -T postgres pg_dump -U microcrm microcrm > "$backup_file"
    echo -e "${GREEN}Backup saved to: ${backup_file}${NC}"
}

# Main menu
main_menu() {
    echo ""
    echo -e "${BOLD}What would you like to do?${NC}"
    echo ""
    echo "  1) Deploy (first-time setup)"
    echo "  2) Stop"
    echo "  3) Restart"
    echo "  4) View logs"
    echo "  5) Status"
    echo "  6) Update (git pull + rebuild)"
    echo "  7) Backup database"
    echo "  8) Reconfigure"
    echo "  9) Exit"
    echo ""
    read -p "Enter your choice [1-9]: " choice

    case $choice in
        1)
            generate_env
            start_services
            ;;
        2)
            stop_services
            ;;
        3)
            echo -e "${BLUE}Restarting services...${NC}"
            $COMPOSE_CMD -f "$COMPOSE_FILE" restart
            echo -e "${GREEN}Services restarted.${NC}"
            ;;
        4)
            show_logs
            ;;
        5)
            show_status
            ;;
        6)
            update_services
            ;;
        7)
            backup_db
            ;;
        8)
            generate_env
            echo -e "${YELLOW}Restart services to apply new configuration.${NC}"
            ;;
        9)
            echo -e "${GREEN}Goodbye!${NC}"
            exit 0
            ;;
        *)
            echo -e "${RED}Invalid choice.${NC}"
            main_menu
            ;;
    esac
}

# Run checks
check_docker

# Handle command line arguments
case "${1:-}" in
    deploy)
        generate_env
        start_services
        ;;
    stop)
        stop_services
        ;;
    logs)
        show_logs
        ;;
    restart)
        $COMPOSE_CMD -f "$COMPOSE_FILE" restart
        ;;
    status)
        show_status
        ;;
    update)
        update_services
        ;;
    backup)
        backup_db
        ;;
    *)
        main_menu
        ;;
esac
